name: Feature request
description: Suggest an improvement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the pain point.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
      placeholder: Describe your proposed approach.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other options you considered.
  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Who benefits and what areas are affected?
  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Links, references, screenshots, or other notes.
