name: Question
description: Ask a usage or design question.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What do you want to know?
      placeholder: Ask your question clearly and include context.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What have you tried so far?
